# Generated by Django 5.0 on 2023-12-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='imgurl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
