# Generated by Django 5.0 on 2023-12-17 13:29

import django.forms.widgets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name=django.forms.widgets.PasswordInput),
        ),
    ]
