# Generated by Django 5.0 on 2023-12-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hallname', models.CharField(max_length=255)),
                ('imgurl', models.URLField()),
                ('price', models.TextField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
